export const FETCH_PROCESS_LOADING = 'FETCH_PROCESS_LOADING'
export const FETCH_PROCESS_SUCCESS = 'FETCH_PROCESS_SUCCESS'
export const FETCH_PROCESS_ERROR = 'FETCH_PROCESS_ERROR'

export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"

export const EDIT_USER_DATA_SUCCESS = "EDIT_USER_DATA_SUCCESS"
export const SUCCESS = "SUCCESS"